version: '3.8'
services:
  db:
    container_name: halostemba_db
    image: postgres:${POSTGRES_VERSION:-latest}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-halostemba}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-h4l0st3mb4}
      POSTGRES_DB: ${POSTGRES_DB:-halostemba}
    env_file:
      - path: .env
        required: true
    ports:
      - '5432:${BIND_PORT:-5432}'
    volumes:
      - ./data:/var/lib/postgresql/data:ro
    network_mode: bridge
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2g
        reservations:
          cpus: 1
          memory: 1g
